labels: ["bugs: confirmado", "exploit"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **ATENÇÃO: RELATÓRIO CONFIDENCIAL DE SEGURANÇA** ⚠️

        Este template é para reportar vulnerabilidades, exploits ou problemas de segurança.
        **NÃO compartilhe publicamente** detalhes de exploits ativos que possam ser abusados.

        A equipe tratará este relatório com prioridade e confidencialidade.

  - type: dropdown
    id: tipo_problema
    attributes:
      label: Tipo de problema de segurança
      description: Qual tipo de vulnerabilidade você descobriu?
      options:
        - Exploit/Duplication (duplicação de itens)
        - Bypass de permissões/comandos
        - Acesso não autorizado
        - Vulnerabilidade de economia
        - Bug de combate/PvP explorável
        - Cheat/Hack detectado
        - Grief/Bypass de proteções
        - Falha de autenticação
        - Injection (comandos, SQL, etc)
        - Crash/DoS exploit
        - Outro
      default: 0
    validations:
      required: true

  - type: dropdown
    id: servidor
    attributes:
      label: Servidor afetado
      description: Qual servidor possui esta vulnerabilidade?
      options:
        - Não especificado (qualquer)
        - Todos os servidores
        - Henesys
        - Vanillew
        - Skyten
        - Lobby
        - Ausevento
        - AusDungeon
        - Discord (bot)
        - Sites ou externos
        - Sistema de login/autenticação
      default: 0
    validations:
      required: true

  - type: dropdown
    id: gravidade
    attributes:
      label: Gravidade estimada
      description: |
        Qual o impacto desta vulnerabilidade?
        Crítica: Pode quebrar a economia ou arruinar o servidor
        Alta: Pode causar dano significativo
        Média: Exploitável mas com impacto limitado
        Baixa: Problema menor de segurança
      options:
        - 🔴 Crítica - Extremamente grave
        - 🟠 Alta - Muito grave
        - 🟡 Média - Moderadamente grave
        - 🟢 Baixa - Pouco grave
      default: 0
    validations:
      required: true

  - type: dropdown
    id: exploracao_atual
    attributes:
      label: Status de exploração
      description: Esta vulnerabilidade já está sendo explorada por jogadores?
      options:
        - ⚠️ SIM - Está sendo explorada ativamente
        - ⚠️ SIM - Poucos jogadores sabem
        - ✅ NÃO - Descobri mas não explorei
        - ❓ NÃO SEI - Não tenho certeza
      default: 2
    validations:
      required: true

  - type: textarea
    id: resumo
    attributes:
      label: Resumo da vulnerabilidade
      description: |
        Explique de forma resumida o problema de segurança.
        NÃO dê detalhes públicos se for um exploit ativo!
      placeholder: |
        Ex: Existe uma forma de duplicar itens usando o sistema de trocas
        Ex: É possível bypassar a proteção de terrenos usando um item específico
        Ex: Comando X pode ser executado sem permissão adequada
    validations:
      required: true

  - type: textarea
    id: passos_reproducao
    attributes:
      label: Passos para reproduzir (CONFIDENCIAL)
      description: |
        Descreva DETALHADAMENTE como reproduzir a vulnerabilidade.
        Quanto mais específico, mais rápido será corrigido.

        ⚠️ Esta seção deve conter informações sensíveis para a equipe corrigir o problema.
      placeholder: |
        1. Pegue o item X no inventário
        2. Abra o menu Y com /comando
        3. Clique no slot Z ao mesmo tempo que...
        4. O item é duplicado no inventário

        OU

        1. Vá para as coordenadas X:100 Y:64 Z:200
        2. Use o comando /tp com o argumento específico
        3. Isso bypassa a proteção e permite acesso ao terreno protegido
    validations:
      required: true

  - type: textarea
    id: impacto
    attributes:
      label: Impacto e consequências
      description: |
        Qual o impacto desta vulnerabilidade?
        O que um jogador mal-intencionado poderia fazer com isso?
      placeholder: |
        Ex: Jogadores podem duplicar itens valiosos infinitamente, destruindo completamente 
        a economia do servidor. Itens raros perdem valor, sistema de shop fica inútil.

        Ex: Permite acesso a áreas privadas, possibilitando roubo e grief de construções 
        protegidas de outros jogadores.
    validations:
      required: true

  - type: textarea
    id: evidencias
    attributes:
      label: Evidências (vídeos, prints, logs)
      description: |
        Anexe evidências que demonstrem a vulnerabilidade.
        Vídeos são especialmente úteis para entender o exploit.

        ⚠️ Não compartilhe publicamente se ainda não foi corrigido!
      placeholder: |
        Ex: [Vídeo demonstrando o exploit - LINK PRIVADO]
        Ex: [Print do item duplicado - arquivo anexado]
        Ex: [Log do console mostrando o erro]
    validations:
      required: false

  - type: textarea
    id: jogadores_envolvidos
    attributes:
      label: Jogadores envolvidos (se souber)
      description: |
        Você sabe de jogadores que estão explorando esta vulnerabilidade?
        Liste nicks se souber (isso ajuda a investigação)
      placeholder: |
        Ex: Vi os jogadores "Player1" e "Player2" usando este exploit
        Ex: Não sei de ninguém usando, descobri por acidente
    validations:
      required: false

  - type: textarea
    id: sugestao_correcao
    attributes:
      label: Sugestão de correção (opcional)
      description: |
        Se você tem ideia de como corrigir, compartilhe aqui.
        Qualquer sugestão técnica é bem-vinda!
      placeholder: |
        Ex: Adicionar validação no comando para verificar permissão antes de executar
        Ex: Desabilitar o uso deste item específico até ser corrigido
        Ex: Adicionar cooldown entre trocas para prevenir duplicação
    validations:
      required: false

  - type: dropdown
    id: divulgacao
    attributes:
      label: Você explorou esta vulnerabilidade?
      description: Seja honesto - não haverá punição por reportar! Isso ajuda a entender o alcance.
      options:
        - Não, apenas descobri
        - Sim, testei algumas vezes para confirmar
        - Sim, usei mas devolvi os itens/vantagens
        - Prefiro não responder
      default: 0
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        **🛡️ Obrigado por ajudar a manter o servidor seguro!**

        Reportar vulnerabilidades de forma responsável ajuda a proteger a comunidade.
        A equipe irá:
        1. Analisar o relatório com prioridade
        2. Desenvolver e aplicar a correção
        3. Investigar possíveis abusos
        4. Creditar você pela descoberta (se desejar)

        **⚠️ LEMBRE-SE:** Não compartilhe detalhes do exploit publicamente até que seja corrigido!