body:
  - type: markdown
    attributes:
      value: |
        💬 **Compartilhe suas ideias com a equipe AusTV!**
        Aqui você pode deixar sugestões, melhorias e conceitos (bem formatados ou não).
        Discutiremos tudo por aqui até que a ideia entre no cronograma de desenvolvimento. 🛠️
  - type: dropdown
    id: servidor
    attributes:
      label: Servidor afetado
      description: Essa ideia é direcionada para qual área?
      options:
        - Todos
        - Discord
        - Sites ou externos
        - Redes sociais
        - Henesys
        - Vanillew
        - Skyten
        - Lobby
        - Ausevento
        - AusDungeon
        - Um novo servidor
      default: 0
    validations:
      required: true
  - type: input
    id: proposito
    attributes:
      label: Qual o propósito da ideia?
      description: |
        Explique o porquê dessa sugestão. Pode ser algo que você viu no Discord ou algo novo que deseja implementar.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Descrição da ideia
      description: Detalhe tudo o que puder sobre sua proposta.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Aplicação
      description: Tem ideia de como aplicar ela no servidor?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Referências
      description: Inclua prints, vídeos ou links que ajudem a ilustrar sua ideia.
    validations:
      required: false
